name: Add New Tag After Merge

on:
  push:
    branches:
      - main

jobs:
  tag-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          root: "./version"
          regex_pattern: "(?<version>(\\d+(\\.)?){3})"
          tag_prefix: "v"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
